templates/featureService.json

Update featureservice.json default description to provide links to Koop

Update featureservice.json defaults

---

gulpfile.js

this fixes complexity reporting.

fix complexity

---

CHANGELOG.md

Fixed a couple things that were breaking markdown rendering. Also improved some wording and added a couple relevant links.

fix change log formatting

---

CHANGELOG.md
index.js
lib/ExportWorker.js
lib/Exporter.js
package.json
test/models/index-test.js

This PR fixes issues with file names on large data exports and makes sure that the dataset status' get updated properly.

Export worker fixes

---

CHANGELOG.md
index.js
lib/ExportWorker.js
lib/Exporter.js
package.json

* Fixing a filtering bug with duplicate VRT files names 
* Adding some docs to the index file 
* fixed the idFilter clause for non-worker exports

Bug fixes for 2.1.1

---

CHANGELOG.md
lib/Exporter.js
package.json

We need to apply a datum xform for proj 2927 before we push koop to prod.

Proj code 2927 xform

---

CHANGELOG.md
lib/ExportWorker.js
lib/Exporter.js
lib/FeatureServices.js
package.json
test/models/exporter-test.js

Fixing projections for UTM datasets (applying the same NAD83 datum xform)
fixing the table flag for geom-less datasets

Proj table fixes

---

CHANGELOG.md
lib/BaseModel.js
lib/Local.js
package.json

A few updates and fixes for supporting geohash aggregation calls to the DB and fixing service registration POSTs when running the local cache.

Basemodel updates for Geohash and Local cache service fixes

---

CHANGELOG.md
lib/FeatureServices.js
lib/GeoJSON.js
lib/Query.js
package.json

Support for returnGeometry=false, and sorting on feature services...
Also trimming CSV headers to remove whitespace

Featureservice fixes

---

CHANGELOG.md
index.js
lib/FeatureServices.js
lib/Logger.js
package.json

Adding 2 file transports for Winston to log errors separately
Fixing a bug with setting the objectIDField in feature service outputs

Object id fix/logs

---

CHANGELOG.md
index.js
package.json

Removes a silly log that got left in while debugging some error logging 
Resolves #170

Log remove

---

CHANGELOG.md
lib/FeatureServices.js
lib/Files.js
package.json

Adds an id field to csv datasets that are missing it. 
Making a head request to s3 for LastModified info to be passed to calls to `koop.Files.exists`

Csv fields

---

CHANGELOG.md
lib/Local.js
package.json

Needed to make provider testing easier

adds check for empty info

---

lib/Exporter.js

Resolves https://github.com/koopjs/koop-opendata/issues/11

more selective about what goes into zip + clean up

---

CHANGELOG.md
lib/Exporter.js
package.json

cleaning up some busted zip creation code...

fixing shp exports; updating changelog and package

---

CHANGELOG.md
lib/BaseModel.js
lib/Exporter.js

Writes a new metadata file in shp exports if the options.metadata exists.

adding exportFile method; writing metadata in shp files; updating changelog

---

CHANGELOG.md
lib/Local.js
test/models/local-cache.js

needed tests and fixes for local cache timers. Were causing trouble in provider tests.

Local timer fix

---

CHANGELOG.md
lib/BaseModel.js
lib/ExportWorker.js
lib/Exporter.js

Saving all files locally into the proper dirs.

Export refactor

---

test/models/basemodel-test.js
test/models/exporter-test.js

making the exporter not need slashes in the shp file format, added a test for it

delinting tests and adding basemodel test

---

RELEASE.md

I added some documentation on the ideal release process.
@jgravois @chelm @dmfenton comments welcome, merge if you're feelin' it

add release doc

---

CHANGELOG.md
public/js/map.js

Addressing half of the problem in https://github.com/koopjs/koop-github/issues/19
@jgravois

fix bug in preview map code

---

CHANGELOG.md
lib/BaseModel.js

A bit of restructuring to how and when responses from the finishExport method are returning

Basemodel logic

---

CHANGELOG.md
lib/Exporter.js
test/models/exporter-test.js

use latest wkid

---

CHANGELOG.md
lib/Exporter.js

removing VRTs in zip files

---

CHANGELOG.md
lib/Exporter.js

Revert "removing VRTs in zip files"

---

lib/BaseModel.js
public/js/map.js
test/models/featureservice-test.js
test/models/files-test.js

add plugin method to model

---

CHANGELOG.md
lib/Exporter.js

function return was not as expected, was causing the basemodel to bomb out on requesting geojson after any other successful export

fix json re-use

---

CHANGELOG.md
lib/ExportWorker.js

ping @ngoldman 
pretty simple here, the changelog says it all

Make export worker concurrency configurable, default to 1

---

CHANGELOG.md
index.js
lib/ExportWorker.js
lib/Files.js
lib/Local.js
lib/Logger.js
package.json
test/fixtures/fake-cache.js
test/fixtures/fake-plugin.js
test/fixtures/fake-provider/index.js
test/helpers/Cache.js
test/models/files-test.js
test/models/index-test.js

Biggest change is a reorg of the index. Code is now grouped in terms of what it does. Should be a lot easier to read and parse (and refactor).
I also set up some logic for better plugin registration handling in the future. See the register, registerProvider, registerCache, and registerPlugin methods hanging off of `app`.
--
* `lib/Files` now takes `options` instead of `koop` (only needed koop.config and koop.log)
* cleaned up `app.register` method logic
* using `koop.log` in index instead of `console.log`
* reorganized index for readability & code organization
* `app.registerProvider` method for providers
* `ejs` is now a dependency ([#234](https://github.com/koopjs/koop/pull/234))
@dmfenton @koopjs/dev

various small fixes, improvements, updates

---

CHANGELOG.md
index.js
lib/BaseModel.js
lib/Cache.js

This was a lot easier than I thought it would be.
I feel like we need to test this more thoroughly since a lot of providers use the insides of koop in weird ways, but all tests are passing, so...
@dmfenton thoughts?

consolidate koop, lib, app

---

index.js

Just a small PR for improving doc and adding todos based on a few things discussed with @dmfenton.

jsdoc for routes

---

lib/BaseModel.js
lib/FeatureServices.js

This adds jsdoc to BaseModel and FeatureServices.
Also removes `attributes` from FeatureServices (not used).
Progress towards finishing #208.

jsdoc for BaseModel and FeatureServices

---

CHANGELOG.md
lib/Query.js

Only major changes are:
* no more use of `this` -- functions call each other directly
* functions attached to module exports at the bottom of the file
* added jsdoc
More progress towards #208.

refactor lib/Query

---

lib/GeoJSON.js
lib/Logger.js

Just adding jsdoc to lib/Logger :smile:

add jsdoc to lib/Logger

---

CHANGELOG.md
lib/Exporter.js

Exclude vrt files from zips

---

lib/Local.js

jsdoc for LocalDB

---

CHANGELOG.md
lib/Files.js

lib/Files: catch `new` omission, add jsdoc

---

CHANGELOG.md

@dmfenton mind if I release 2.8.6 with the LocalDB fix after this? It's a blocker for the continuous deployment webhook project I'm working on (https://github.com/ngoldman/koop-lab).

fix compare link

---

CHANGELOG.md
lib/ExportWorker.js

Title says it all.
cc @jwieringa @brooksjbr

adds error logging to export worker

---

.changeset/clean-owls-grin.md
.changeset/dull-trains-decide.md
.changeset/empty-apes-sniff.md
.changeset/good-bikes-float.md
.changeset/mighty-planes-draw.md
.changeset/shiny-trainers-scream.md

Add changesets to bump all packages a major version for initial monorepo release.

chore: do new monorepo release

---

.changeset/eleven-clouds-report.md

Revert "chore: logger release"

---

.changeset/clean-owls-grin.md
.changeset/dull-trains-decide.md
.changeset/empty-apes-sniff.md
.changeset/good-bikes-float.md
.changeset/mighty-planes-draw.md
.changeset/shiny-trainers-scream.md

chore: changesets

---

.changeset/cache-memory.md
.changeset/featureserver.md
.changeset/koop-core.md
.changeset/logger.md
.changeset/output-geoservice.md
.changeset/winnow.md
.github/workflows/release.yml

Revert "chore: bump release"

---

.changeset/khaki-jokes-roll.md
.changeset/slimy-beans-move.md
packages/featureserver/package.json
packages/featureserver/src/query/filter-and-transform.js
packages/featureserver/src/query/filter-and-transform.spec.js
packages/winnow/package.json
packages/winnow/src/sql-query-builder/select/index.js
packages/winnow/src/sql-query-builder/select/index.spec.js

- Adds a "distinct" option to the Winnow package; when true, queries will be like `SELECT DISTINCT`
- Add support for `returnDistinctValues` to FeatureServer

feat(): support DISTINCT query

---

.changeset/sharp-news-drop.md
packages/featureserver/src/helpers/data-type-utils.js
packages/featureserver/src/helpers/data-type-utils.spec.js

fixes: https://github.com/koopjs/koop/issues/469

fix: string-conversion

---

.changeset/gold-bats-pump.md
.changeset/stupid-hounds-look.md
packages/featureserver/package.json
packages/featureserver/src/helpers/fields/statistics-fields.js
packages/featureserver/src/helpers/get-collection-crs.js
packages/featureserver/src/helpers/get-collection-crs.spec.js
packages/winnow/src/normalize-query-options/spatial-reference.js
packages/winnow/src/sql-query-builder/select/geometry-select-fragment.js

CodeQL analysis identified a few inefficient regex patterns.  Fixed here.

Cleanup regexs

---

.changeset/itchy-trains-admire.md
.changeset/quick-impalas-build.md
package-lock.json
packages/featureserver/package.json
packages/featureserver/src/query/render-precalculated-statistics.js
packages/winnow/src/normalize-query-options/helpers/get-collection-crs.js

A trio of fixes:
- use isDate function from helpers
- replace inefficient regex
- explicitly add koop-logger to feature-server

fix(): regex, date parser, logger

---

.changeset/breezy-beans-sing.md
packages/featureserver/src/helpers/normalize-request-params.js
packages/featureserver/src/helpers/normalize-request-params.spec.js

PR for https://github.com/koopjs/koop/issues/605

fix: coerce POST body parameters

---

.github/workflows/ci-tests.yml
package.json

Adds windows to CI test regime.

chore: add windows to CI

---

.github/workflows/next-pr.yml

automate pr request generation on `next` branch update.

chore: a next-pr-action

---

package-lock.json
packages/cache-memory/package.json
packages/featureserver/package.json
packages/logger/package.json
packages/winnow/package.json

No release required.  Only minor/patch updates to package.json files.

Update patch/minor dependencies

---

packages/featureserver/coverage-unit.svg
packages/featureserver/coverage.svg
packages/featureserver/src/query/log-warnings.js
packages/featureserver/src/query/log-warnings.spec.js

refactor: featureserver debug messages

---

packages/winnow/package.json

Revert 738 dependabot/npm and yarn/packages/winnow/next/joi tw 17.10.1

---

.github/dependabot.yml
.github/workflows/dependabot-auto-merge.yml

- simplify dependabot update groups; merge minor/patch dev and prod groups
- fix conditional in dependabot auto-merge GH action

Dependabot management

---

CONTRIBUTING.md
README.md

docs: contributing

---

.github/workflows/ci-tests.yml
test/geoservice-client-requests-no-geom.spec.js
test/helpers/client-response-fixtures.js

e2e test fixture had an error in description text.

fix: e2e test fixtures

---

test/geoservice-client-requests-no-geom.spec.js
test/geoservice-defaults.spec.js
test/helpers/client-response-fixtures.js

Add final parameterized e2e test parameter.

test: parameterize copyright text

---

ci/format-branch-coverage-changes.js
package.json

`require` path was incorrect for json file import.

fix: fix path to coverage summary

---

.changeset/neat-lizards-nail.md
packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.js
packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.spec.js

This PR will debug-log idField warnings due to data-type and integer range separately.

fix: separate idField debug messages

---

.changeset/rich-numbers-judge.md
.changeset/silver-eagles-explain.md
packages/core/src/data-provider/extend-model.js
packages/output-geoservices/README.md
packages/output-geoservices/src/index.js
packages/output-geoservices/src/index.spec.js

See:
- https://github.com/koopjs/koop/issues/978
- https://github.com/koopjs/koop/issues/979

fix: two auth bugs
