koopjs/koop

.travis.yml, CHANGELOG.md, README.md, license.txt, package.json
I updated the change log to reflect fixes to releases (#116) and added compare links to version titles (free version diffing, woo).
I also updated `.travis.yml` to target `0.10` and `0.12` only (since the docs say "Node.js (version > 0.10.0)" and 0.12 is the new stable release) as well as enabling caching and docker containers to speed up tests (#114).
I also fixed the link to the license in the readme and replaced an illegal character in `license.txt`.
> resolves #114 & #116
=> update CHANGELOG.md & .travis.yml

.gitignore, README.md, package.json
I learned recently that you don't need to prefix bin paths to installed modules with `node_modules/**/**`.
`lint` script now just uses gulp, so you can run `npm run lint` and it will delegate to gulp. This also circumvents needing to install gulp globally.
Added a badge to show latest version published to npm. Also using flat badge style from http://shields.io for added futurism (looks like this: https://github.com/ngoldman/koop/tree/tweaks#koop).
Ignoring complexity output for git. @JerrySievert I'm noticing the HTML reporter doesn't seem to be generating anything right now so it's not super useful.
=> minor tweaks to package.json & readme

CHANGELOG.md, lib/ExportWorker.js, lib/Exporter.js, package.json
We need to handle small datasets a bit differently in the export workers for Open Data. The export stuff is still in need of more refactoring but this will close an issue with data exports only when using export workers and forcing small data to go to the worker q
=> Small exports

CHANGELOG.md, lib/Exporter.js, package.json
There is an open issue in GDAL/ogr2ogr around Esri projection strings for Lamert_Conformal_Conic WKT. The fix is to add "_1SP" which sets the standard pararrel param and allows data with this proj to project correctly. 
more info: http://trac.osgeo.org/gdal/ticket/2072
=> forcing Lambert_Conformal_Conic_1SP on lambert proj strings

CHANGELOG.md, lib/Exporter.js, package.json
* Sanitizing export file names to protect again quotes in input params to ogr2ogr
* Better protection against missing proj codes in the esri-proj-code lookup
=> Fixes from qa smoketests

CHANGELOG.md, lib/ExportWorker.js, lib/Exporter.js
More crucial fixes for 2.1.0 before I publish the release. The reason that this is v2.1.0 is due to the change in the way offset/limits pagination on large data exports is handled. Koop exports now use a WHERE clause based paging structure that is free of the poor performance you get from using high OFFSET values.
=> Export worker fixes

CHANGELOG.md, lib/Exporter.js, lib/FeatureServices.js, package.json
If a dataset has saved an array of fields the Koop featureservice code will use that for its list of fields. This preserves the original original field order from CSV data.
=> ordered fields if header info is saved

README.md, ROADMAP.md
I moved instructions on developing providers out of the readme and into documentation here: https://github.com/koopjs/koopjs.github.io/blob/master/docs/specs/provider.md
Also corrected some errors, edited some copy, and improved on the structure of the readme as a whole.
I removed version numbers from the roadmap as I don't think it makes sense to tie implementation plans to specific versions (unless we want to plan a specific major version). Version numbers will change as bugs are fixed and contributions are added. Using the roadmap as a guide rather than a contract will probably make life easier for us (and require us to update version number targets in there a lot less frequently).
@koopjs/dev let me know if this looks alright.
=> improve readme, edit roadmap

CHANGELOG.md, lib/BaseController.js, lib/BaseModel.js, lib/Cache.js, lib/FeatureServices.js, lib/Query.js, test/models/featureservice-test.js
Added a severat small things. More docs, more cache wrapping methods form pgcache and a few optimizations to the featureservice requests. 
One change/addition of note is the ability for providers to optionally pass in an "overrides" object on the `req.query` that will override any properties on the resulting feature service JSON. This was a user request that wanted to be able to change things like the name and description of the service...
=> Fs optimizations

CHANGELOG.md, index.js
Creates an empty config object if none is passed. The files that were crashing koop before always check for params so all we needed to do was have a short circuit for the config object in the index.js 
closes #186
=> fixing the zero config crashing bug

CHANGELOG.md, lib/BaseModel.js, lib/Exporter.js, lib/SpatialReference.js, test/models/exporter-test.js
Instead of reprojecting data using a WKT or WKID via the query string we support an outSR param that get parsed and normalized to support different variations of json spatial references.
=> Using out sr

CHANGELOG.md, lib/Exporter.js
This brings back support for wkid, and wkt in addition to supporting outSR. If any of those are present koop will attempt to reproject SHP exports. This mean reprojection is still "on-demand" and providers can choose when a dataset gets re-projected.
=> Wkt wkid out sr

CHANGELOG.md, lib/ExportWorker.js, lib/Exporter.js, test/models/exporter-test.js
Some issues with lib/* refactor cropped up in the ExportWorker. It was mostly an issue with creating the idFilter that gets used when paging over the Cache while exporting data. I fixed the issues and added a test around the logic for creating the idFilter.
=> Exporter fixes

CHANGELOG.md, index.js
This will give us more of a clue of what's going on when Koop gets initialized.
Logs Koop version and mountpath when `app.use(koop)` gets called in an express app.
Makes "missing type property" warning more informative.
So now we see some useful info on startup:
```
info: registered cache: postgis 1.1.0
warn: Plugin "Gist" missing type property. Defaulting to provider.
warn: No Github token in config for Gist provider. This may cause problems accessing data.
info: registered provider: Gist 1.0.1
info: Koop 2.6.2 mounted at /
```
=> minor log improvements

CHANGELOG.md, lib/Cache.js, test/models/cache-test.js
This PR sends sort options down to the db where it belongs. Previously if you used a sort and a limit simeltaneously you risked getting the wrong features if there are more features than the limit. This occured because sorting was only happening after features were retreived.
There is also the start here to functions that belong in a "geoservices interface" since we don't yet know what the structure/API for an interface is, I think this is the best place for these two functions for now.
What do you think @ngoldman?
=> Use DB sorting instead of in-memory sorting

CHANGELOG.md, lib/Exporter.js, test/models/exporter-test.js
This fixes a regression in the code used to correct the 2927 query string. There is an issue with the way ArcGIS server transforms data from 2927 to WGS84 that requires a datum transformation to get back to 2927.
=> fix regression in 2927 WKT string

CHANGELOG.md, lib/Exporter.js, lib/Query.js, test/models/exporter-test.js
Adds a `-nlt {geometry_type}` parameter to the OGR calls so that shapefiles can still be written sucessfully even when the first geometry in a table is null
=> fix bug with null geometry

.travis.yml, CHANGELOG.md, lib/Exporter.js, test/models/exporter-test.js
This PR fixes a couple related bugs around exporting geometry with OGR2OGR. Previously we only checked the first feature for geometry, now we check for the first non-null geometry.
@koopjs/dev
=> fixes and better tests for exporting geometry

CHANGELOG.md, lib/templates/featureLayer.json
This resolves a small bug in ArcGIS Open Data where the map display field value shows up as undefined because the "id" field does not exist. Now Open Data can just choose the first non-objectID field.
=> dont set display field that doesnt exist

CHANGELOG.md, index.js, lib/ExportJob.js, lib/ExportQueue.js, lib/ExportWorker.js, lib/Exporter.js, lib/Files.js, lib/index.js, package.json, test/models/exportJob-test.js, test/models/exporter-test.js, test/models/index-test.js
This is marked DNM because it's ready for review but needs to go through integration testing.
The main goal of this refactor was to remove the ambiguous `status: processing` when a resource is being exported to a format.
Instead the info doc will look like
``` json
{
"generating": {
"key1": {
"progress": "50%"
},
"key2": {
"progress": "100%",
"zip": true,
"kml": true
}
}
}
```
`Progress` is created by an export job pulling rows from the database and writing them to json. The `format: true` indicates that a file format export is either in progress or has been completed. These values serve to create implicit export locks that do no allow new jobs to be created when they shouldn't be.
Also during this refactor I broke ExportWorker up into many smaller functions and removed extraneous updates …
=> Refactor of Export Workers

CHANGELOG.md, lib/GeoJSON.js, test/models/geojson-test.js
Null dates are no longer set to the ISO string for 1970...
cc @astauffer
=> fix bug with null dates

CHANGELOG.md, lib/Cache.js
This PR adds support for adding indexes to a DB table. Currently only supported by PG-Cache
=> support for adding indexes

README.md
The link resulted in a 404 before, updated the link to match the link from the top-level github.io page.
=> Update broken Koop Documentation Link

.commitlintrc.js, .gitignore, .husky/commit-msg, .husky/pre-commit, package-lock.json, package.json
Adding in:
- commit-msg hook to ensure commits use conventional-commit format
- a `precommit` script that executes lint-staged and unit tests
- a `commit` script that uses cz-git to prompt users with interface for commit messages
Note: the cz-git library automatically runs `npm run precommit` _before_ prompting user for commit message input.  This is desirable, because any failed lint or unit test can be detected _before_ the user puts forth the effort to construct the commit message.  It also means we don't need a separate pre-commit hook, so this PR deletes the existent pre-commit hook.
=> Commit tooling

package-lock.json, package.json
Reverts koopjs/koop#422.  Jest 29 requires Node > 12, and we still want to support 12.
=> Revert "chore(deps): update dependency jest to v29"

.changeset/calm-lizards-float.md, packages/koop-core/src/index.spec.js, packages/output-geoservices/src/index.js
Routes with a `/rest/services` fragment were added to the output-geoservices plugin in April of 2018 when it became clear that ArcGIS clients required them to work properly with Koop.  We left the legacy routes (those without `/rest/services`) to ensure backward compatibility.  However, having two sets of routes has created confusion for users - especially when then attempt to use the legacy routes with and ArcGIS client and get failures.  After 4 1/2 years, it seems it is a fair time to remove these routes.
BREAKING CHANGE: remove legacy feature server routes
=> refactor(output-geoservices): remove legacy feature server routes

.changeset/calm-lizards-float.md, packages/koop-core/src/index.spec.js, packages/output-geoservices/README.md, packages/output-geoservices/package.json, packages/output-geoservices/src/index.js
Same as https://github.com/koopjs/koop/pull/432 - which failed due to issue with CI/CD.
=> Remove legacy geoservice routes

.changeset/cold-eyes-flow.md, .changeset/gorgeous-schools-beam.md, .changeset/sharp-boxes-suffer.md, packages/koop-core/src/index.js, packages/koop-core/src/provider-registration/create-controller.js, packages/koop-core/src/provider-registration/index.js, packages/koop-core/src/provider-registration/index.spec.js, packages/koop-core/src/provider-registration/provider-output-route.spec.js, packages/logger/src/index.js, packages/output-geoservices/src/index.js
The PR:
- fixes a bug in how the koop-logger code was being required.
- refactors setting of log-level and allows it to be set via the configuration object
- allows a custom logger to be passed into koop-core
- passes the koop-logger to all output-plugin instances
=> feat: allow use of custom logger

.changeset/fresh-chefs-destroy.md, packages/featureserver/src/query/render-features.js, packages/featureserver/src/query/render-features.spec.js
This sets `hasZ` in the query response based on the feature metadata from the provider model, defaulting to false to maintain previous behavior if `metadata.hasZ` is not set.
Fixes #452
=> fix: set hasZ from feature metadata in query handler

.changeset/hot-dots-doubt.md, packages/koop-core/src/provider-registration/create-model.js, packages/koop-core/src/provider-registration/create-model.spec.js
Makes the provider registration `options` object explicitly available on the provider's Model constructor.
=> feat(): support explicit options argument in provider Model constructor

.changeset/plenty-cobras-repair.md, packages/koop-core/coverage.svg, packages/koop-core/src/provider-registration/create-model.js, packages/koop-core/src/provider-registration/create-model.spec.js
Updates the model.pull method to use new cache metadata property `_cache` when available.
=> fix(): use new cache info when available

.changeset/nervous-panthers-exist.md, demo/provider-data/point-fc.geojson, package-lock.json, package.json, packages/featureserver/coverage-unit.svg, packages/featureserver/coverage.svg, packages/featureserver/src/error.js, packages/featureserver/src/geoservice-error.js, packages/featureserver/src/response-handler.js, packages/featureserver/src/route.js, packages/featureserver/src/route.spec.js, packages/featureserver/test/integration/route.spec.js, packages/koop-core/coverage.svg
The PR wraps FeatureServer response errors according to the ArcGIS specification and gives them a 200 status.  Weird, I know, but that's what ArcGIS client's expect.
=> fix: wrap FeatureServer errors according to ArcGIS spec

.changeset/honest-cats-own.md, .changeset/nervous-panthers-exist.md, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.js, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.spec.js, packages/winnow/test/integration/filter.spec.js, packages/winnow/test/integration/to-esri.spec.js
When tasked with transform GeoJSON to Esri JSON, Winnow may attempt to create an OBJECTID for each feature (if one doesn't exist) by hashing the feature.  In addition, it was convert any stringified date properties to epoch time (as per normal ArcGIS server practice for dates).
It is important that date transforms occur after the OBJECTID hashing, so that the OBJECTID gets created by the original feature.  That's because subsequent filtering/comparisons of that OBJECTID expect that it was created from the original feature data, without date transforms.
This PR moves date transforms so that they occur after hashing.
=> Create numeric hash of feature before date transformations

.changeset/cyan-apricots-tie.md, demo/provider-data/point-cached.geojson, package-lock.json, packages/koop-core/README.md, packages/koop-core/coverage.svg, packages/koop-core/package.json, packages/koop-core/src/index.js, packages/koop-core/src/index.spec.js, packages/koop-core/src/provider-registration/create-model.js, packages/koop-core/src/provider-registration/create-model.spec.js, packages/koop-core/src/provider-registration/index.js, packages/koop-core/test/fixtures/fake-provider/models/fake.js
- Add cacheSize options to Koop instance options; this will override the default LRU cache size (500)
- Add cacheTtl options to provider registration options; if set, this is the default cache time for any data from a given provider
- - Make some model props private; these will still be available in the provider's class methods.
=> feat: private model props

package.json, test/geoservice-error-handling.spec.js, test/geoservice-query.spec.js
Add mock-logger in E2E test to prevents confusing logs during test runs.
=> chore: add mock logger

.changeset/hungry-tips-switch.md, .github/workflows/synk-dep-check.yml, package-lock.json, packages/winnow/package.json
Winnow is missing the @koopjs/logger dep in its package.json.  This would likely cause a runtime error if winnow package was used as a standalone.
=> fix: need logger dep in winnow package

.changeset/funny-beds-doubt.md, .changeset/gold-islands-perform.md, demo/index.js, packages/featureserver/src/helpers/calculate-extent.js, packages/featureserver/src/helpers/feature-layer-metadata.js, packages/featureserver/src/helpers/fields/fields.js, packages/featureserver/src/helpers/get-geometry-type-from-geojson.js, packages/featureserver/src/helpers/normalize-spatial-reference.js, packages/featureserver/src/helpers/server-metadata.js, packages/featureserver/src/helpers/validate-inputs.js, packages/featureserver/src/helpers/validate-inputs.spec.js, packages/featureserver/src/logger/index.js, packages/featureserver/src/logger/logger.js, packages/featureserver/src/query/log-warnings.js, packages/featureserver/src/route.js, packages/featureserver/src/server-info-route-handler.js, packages/winnow/src/filter-and-transform/filters/hashed-objectid-comparator.js, packages/winnow/src/filter-and-transform/transforms/project.js, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.js, packages/winnow/src/logger/index.js, packages/winnow/src/logger/logger.js, packages/winnow/src/normalize-query-options/geometry-filter-spatial-reference.js, packages/winnow/src/normalize-query-options/id-field.js, packages/winnow/src/normalize-query-options/limit.js, packages/winnow/src/normalize-query-options/output-data-spatial-reference.js, packages/winnow/src/normalize-query-options/source-data-spatial-reference.js, packages/winnow/src/normalize-query-options/spatial-reference.js
Default loggers in FeatureServer and Winnow are overridden by Koop logger when FeatureServer is registered.  As a result, the logger needs to accessed at request time, because in such cases the logger instance (with associated log level, formatting, etc) has changed.
=> Acquire logger at request time in FeatureServer and Winnow

.changeset/mighty-ravens-bathe.md, packages/featureserver/src/metadata-defaults.js
This PR allows null values or empty strings as overrides for the geoservicesDefaults options: `description`, `serviceDescription`, `copyrightText`.
=> fix: allow empty strings in geoservices defaults

.changeset/modern-pets-press.md, packages/featureserver/src/response-handler.js
The `callback` query param gets sanitized when present, but currently there is no type checking.  This means there would be a request time-error if the value's type was not a string.
The PR adds type-checking.
=> Check callback type 

.changeset/smooth-baboons-bathe.md, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.js, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.spec.js, packages/winnow/src/normalize-query-options/object-ids.js, packages/winnow/src/normalize-query-options/object-ids.spec.js, packages/winnow/src/sql-query-builder/where-builder/index.js, packages/winnow/src/sql-query-builder/where-builder/index.spec.js, packages/winnow/src/sql-query-builder/where-builder/to-json-where.spec.js, test/geoservice-client-requests-provider-w-string-id-field.spec.js, test/geoservice-query.spec.js, test/provider-data/points-w-metadata-id-string.geojson
See https://github.com/koopjs/koop/issues/803.
This PR allows string attributes to be used as the  unique-id in Koop Feature Services.
=> feat: allow strings as unique-identifier

.changeset/orange-readers-sip.md, .changeset/rude-frogs-sneeze.md, packages/featureserver/src/query/log-warnings.js, packages/featureserver/src/query/log-warnings.spec.js, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.js, packages/winnow/src/filter-and-transform/transforms/to-esri-attributes.spec.js, test/geoservice-query.spec.js
- fix messaging about "no idField" when OBJECTID is already a property in the GeoJSON; this message should be omitted under these conditions
- when messaging about the range of the OBJECTID, it should be the MAX_SAFE_INTEGER value
=> fix: log messages for idField and integer range

test/geoservice-client-requests-no-geom.spec.js, test/geoservice-defaults.spec.js, test/helpers/client-response-fixtures.js
- revert params by process.env, but leave `const` defs
=> test: simplify e2e params

.changeset/friendly-waves-wink.md, packages/featureserver/coverage-unit.svg, packages/featureserver/package.json, packages/featureserver/src/helpers/data-type-utils.js, packages/featureserver/src/helpers/data-type-utils.spec.js, packages/winnow/coverage.svg
Convert of YYYY-MM-DD hh:mm:ss.s to epoch time.  Labeling and releasing as a patch, given it was likely a regression from functionality in pre-monorepo Koop.
=> fix: convert YYYY-MM-DD hh:mm:ss.s to epoch time

.changeset/beige-lemons-beg.md, packages/core/src/index.js
This PR passes a logger (either the cache registration option or the koop instance logger) in the cache plugin constructor.
=> feat: pass logger into cache plugin constructor

.changeset/silver-trainers-promise.md, packages/cache-memory/src/index.js, packages/cache-memory/src/index.spec.js
The PR does some refactoring on the memory-cache package:
- replace callback usage with async/await
- remove the normalizeGeojson function - actually not needed since the cache spec was simplified
=> refactor: memory-cache

.changeset/eleven-games-cross.md, packages/featureserver/src/query/validate-query-request-parameters.js
Fixes a bug in Esri's AGOL Map Viewer where the .pbf tiles will not load due to the request coming with a quantizationParameter containing "mode".
=> Quantization mode

.changeset/fluffy-grapes-serve.md, package-lock.json, packages/winnow/package.json, packages/winnow/src/filter-and-transform/helpers/hash-function.js, packages/winnow/src/filter-and-transform/helpers/hash-function.spec.js
Swap out string-hash for murmurhash; more performant less chance for collisions.
=> feat: update hash function

.changeset/three-actors-try.md, packages/featureserver/coverage-unit.svg, packages/featureserver/src/query/filter-and-transform.js, packages/featureserver/src/query/filter-and-transform.spec.js, packages/featureserver/src/query/index.js, test/geoservice-query.spec.js
GeoServices API specification allows a `where` that uses `+` as a placeholder for whitespace. So something like this is valid:
`where=Foo+IS+NOT+NULL`
The current release of Koop rejects `where` params that are constructed with the `+` delimiter.  This PR patches this limitation.
=> Handle "where" param with +

.changeset/lazy-wombats-relate.md, demo/provider-data/points-w-metadata-id-string.geojson, packages/featureserver/coverage-unit.svg, packages/featureserver/coverage.svg, packages/featureserver/src/response-handlers/helpers/send-pbf/transform-to-pbf-attributes.js, packages/featureserver/src/response-handlers/helpers/send-pbf/transform-to-pbf-attributes.spec.js
Koop allows use of strings as OBJECTIDs.  While ArcGIS OBJECTIDs are supposed to be integers, many ArcGIS clients seem to work without issue if OBJECTIDs or FIDs are strings.  Big exception is ArcGIS Pro - it fails with datasets that don't use integers.
The currently released PBF encoder in Koop doesn't properly encode string OBJECTIDs.  This results in 0 values for the OBJECTIDs when decoded by clients.  The PR fixes.
=> fix: allow proper encoding of string OIDs in PBF format

.changeset/big-pets-search.md, .changeset/kind-students-move.md, .changeset/plenty-ligers-vanish.md, .changeset/twenty-gifts-fly.md, packages/featureserver/coverage-unit.svg, packages/featureserver/coverage.svg, packages/featureserver/src/query/render-features.js, packages/featureserver/src/query/render-features.spec.js, packages/featureserver/src/route.spec.js, packages/featureserver/test/integration/route.spec.js, packages/winnow/coverage-unit.svg, packages/winnow/src/normalize-query-options/limit.js, packages/winnow/src/query/standard-query.js, packages/winnow/src/query/standard-query.spec.js, packages/winnow/test/integration/to-esri.spec.js, test/geoservice-query.spec.js, test/provider-data/pass-through.geojson
Some ArcGIS clients use `exceededTransferLimit` property on query responses to determine if they should request another page of data.  The origin of the value for this field is deep in the Koop dependency chain (Winnow) where the in-memory feature collection is truncated to fit the `resultRecordCount` parameter.  However, pass-through providers may do their own truncation based on `resultRecordCount` and as a result, never go through Winnow.  In such cases, `exceededTransferLimit` will always have a value of `false`, even if it should be `true`.  Providers need a way of setting `exceededTransferLimit: true` when they handle their own truncation.
In this PR, I add the ability for data providers to control the value of `exceededTransferLimit` by adding it to the geojson metadata.  
```js …
```
=> feat: set exceededTransferLimit in metadata

.changeset/hungry-queens-battle.md, package-lock.json, package.json, packages/featureserver/src/response-handlers/helpers/send-pbf/index.js, packages/featureserver/src/response-handlers/helpers/send-pbf/index.spec.js, test/geoservice-pbf.spec.js, test/helpers/FeatureCollection.proto.js
Addresses report of header error here: https://github.com/koopjs/koop/issues/922.
=> chore: change pbf header write

ci/format-branch-coverage-changes.js
New files throw an undefined error in CI script that generates coverage report for PR.
=> fix: handle new files in cov report

.changeset/late-meals-provide.md, packages/core/src/data-provider/index.js
Provider registration allows for the `before` and `after` options; these are functions that can be used to transform the incoming request _before_ it arrives at the `getData` method or transform the geojson _after_ it is passed out of the `getData` method.  When originally implemented these methods had to use callback form and they were invalid unless they had two (_before_ function ) and three (_after_ function) arguments.  Callback was the last argument for each of course. However, we now allow the use of `async` and as a result it would be valid if the _before_ function had one arg, and the _after_ had two.  This PR removes argument length validation from these function as it doesn't seem worth the complexity.
=> fix: remove arity validation for provider transforms

.changeset/modern-dryers-hang.md, packages/output-geoservices/src/index.js, packages/output-geoservices/src/index.spec.js
Recent refactor did not properly handle the `Invalid URL` response required on /MapServer route.
=> output-geoservices fix: handle invalid url

.changeset/soft-pans-deny.md, package-lock.json, packages/winnow/coverage-unit.svg, packages/winnow/coverage.svg, packages/winnow/package.json, packages/winnow/src/filter-and-transform/filter-and-transform.spec.js, packages/winnow/src/filter-and-transform/filters/contains.js, packages/winnow/src/filter-and-transform/filters/contains.spec.js, packages/winnow/src/filter-and-transform/filters/envelope-intersects.js, packages/winnow/src/filter-and-transform/filters/envelope-intersects.spec.js, packages/winnow/src/filter-and-transform/filters/helpers.js, packages/winnow/src/filter-and-transform/filters/intersects.js, packages/winnow/src/filter-and-transform/filters/intersects.spec.js, packages/winnow/src/filter-and-transform/filters/within.js, packages/winnow/src/filter-and-transform/filters/within.spec.js, packages/winnow/src/normalize-query-options/geometry-filter.js, packages/winnow/src/sql-query-builder/where-builder/index.js, packages/winnow/src/sql-query-builder/where-builder/index.spec.js, packages/winnow/test/integration/filter.spec.js, test/geoservice-query.spec.js, test/provider-data/diagonal-feature.geojson, test/provider-data/multi-polygon.geojson
Recent testing shows that in certain circumstances, filtering by geometry did not work as it should.  The test case that surfaced the initial issue was:
**Context:**
dataset type:  `Multipolygon` feature collection
geometry filter: `envelope`
spatial relation: `intersects`
When the filter envelope completely contained one of the multi-polygon features, it was found to be excluded from the returned feature set.  
Following this discovery I performed an audit on all of Koop's supported geometric filtering operations: intersects, contains, within.  I found the `within` implementation to be incorrect.  Extensive testing on ArcGIS Server indicates:
- `within`: return any features that this search geometry is found within
- `contains`: return any features contained within this search geometry
- …
=> fix: faulty geometric filtering

.changeset/polite-lions-protect.md, packages/featureserver/src/response-handlers/helpers/send-pbf/transform-to-pbf-geometry.js
Quanitzation applied to PBF encoding needs to strip out single vertex rings/paths that can occur when quantization scaling occurs at wide extents.  Leaving these single vertex rings/paths results in fault geometry.  See below:
=> fix: remove single vertex rings and paths from quantized geometry

.changeset/strange-avocados-guess.md, packages/winnow/coverage-unit.svg, packages/winnow/src/calculate-class-breaks/index.js, packages/winnow/src/calculate-class-breaks/index.spec.js, test/geoservice-generate-renderer.spec.js
Fix for https://github.com/koopjs/koop/issues/1019.
=> fix: classifier break count must >= features.length - 1

.changeset/grumpy-boats-crash.md, packages/featureserver/src/query/validate-query-request-parameters.js, packages/featureserver/src/query/validate-query-request-parameters.spec.js
FeatureServer should allow outputting geojson as a valid schema.
@rgwozdz
=> fix: adding back support for geojson as an output schema

.changeset/smart-keys-prove.md, packages/winnow/src/sql-query-builder/where-builder/index.js
This resolves an issue where filtering for object ids using the objectIds query parameter with a layer definition applied that also filters for object ids doesn't return the expected results.  The existing regex for filtering `IN` predicates was too lenient and captured the 2nd part of where clauses as well in the value capture group.
ex.
```
properties->`OBJECTID` IN (148985057, 186921065, 1215860827, 1157475985, 713444784 ) AND properties->`OBJECTID` IN (713444784 )
```
```
hashedObjectIdComparator(properties, geometry, '148985057,186921065,1215860827,1157475985,713444784)ANDproperties->`OBJECTID`IN(713444784', 'IN')=true
```
```
hashedObjectIdComparator(properties, geometry, '148985057,186921065,1215860827,1157475985,713444784', 'IN')=true AND hashedObjectIdComparator(properties, …
```
=> Fix issue with object id queries

.changeset/silent-dodos-tie.md, packages/core/src/data-provider/extend-model.js, packages/core/src/data-provider/extend-model.spec.js
The default generator was ignoring variances between `GET` & `POST` methods. This caused `POST` requests to get cached incorrectly. Now, both the request query and body are loaded and merged into a common object and stringified as part of the key generation omitting query params from the url string.  This will make the url be the same between `GET` and `POST` and allow for the parameters to be common when submitted into the hasher function.
I also updated the hasher method to use the larger hash size to help prevent collisions since large datasets can be submitted in as part of the caching data.  Users of the api can submit in large sets of `OBJECTIDS` and Geometry as part of query parameters.  This should help mitigate any cache collisions.
I added some new unit tests to verify that …
=> Fixed default Model cache key generation issue
